language: ruby
bundler_args: --without development
rvm:
  - 2.0.0
  - 1.9.3
gemfile:
  - .gemfiles/Gemfile.mongoid4
notifications:
  recipients:
    - jerry.clinesmith@koanhealth.com
services:
  - mongodb
